openapi: 3.0.3
info:
  title: 'My TuBao Makeup Laravel API Documentation'
  description: 'This is the documentation for the My Tubao Makeup Laravel API.'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/appointments:
    get:
      summary: 'API method to fetch appointments for the authenticated user with optional search.'
      operationId: aPIMethodToFetchAppointmentsForTheAuthenticatedUserWithOptionalSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>today</code>.'
                  example: '2116-10-10'
                  nullable: false
                time:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i</code>.'
                  example: '23:26'
                  nullable: false
                service_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the services table.'
                  example: soluta
                  nullable: false
              required:
                - date
                - time
                - service_id
      security: []
  '/api/appointments/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  description: 'Must be a valid date. Must be a date after or equal to <code>today</code>.'
                  example: '2055-07-03'
                  nullable: false
                time:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i</code>.'
                  example: '23:26'
                  nullable: false
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the appointment.'
        example: nihil
        required: true
        schema:
          type: string
  /api/admin/bookings:
    get:
      summary: ''
      operationId: getApiAdminBookings
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/admin/bookings/{id}':
    get:
      summary: 'Show the specified booking.'
      operationId: showTheSpecifiedBooking
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the booking.'
        example: architecto
        required: true
        schema:
          type: string
  '/api/admin/bookings/{id}/approve':
    patch:
      summary: 'Approve the specified booking.'
      operationId: approveTheSpecifiedBooking
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the booking.'
        example: aut
        required: true
        schema:
          type: string
  '/api/admin/bookings/{id}/reject':
    patch:
      summary: 'Reject the specified booking.'
      operationId: rejectTheSpecifiedBooking
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the booking.'
        example: eveniet
        required: true
        schema:
          type: string
  /api/appointments/search:
    get:
      summary: ''
      operationId: getApiAppointmentsSearch
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: nkreiger@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: autem
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
